<!doctype html>
<html>
<head>
  <title>WEB - JavaScript</title>
  <meta charset="utf-8">
</head>


<body>
  <h1><a href="index.html">WEB</a></h1>
  <ol>
    <li><a href="1.html">HTML</li>
    <li><a href="2.CSS">JavaScript</a></li>
    <li><a href="3.JavaScript">CSS</a></li>
  </ol>

  <h2>안녕하세요</h2>
    <p>The name cascading comes from the specified priority scheme to determine which style rule applies if more than one rule matches a particular element. This cascading priority scheme is predictable.
    The CSS specifications are maintained by the World Wide Web Consortium (W3C). Internet media type (MIME type) text/css is registered for use with CSS by RFC 2318 (March 1998). The W3C operates a free CSS validation service for CSS documents.[5]
    In addition to HTML, other markup languages support the use of CSS including XHTML, plain XML, SVG, and XUL</p>
</body>
</html>
